### ISSUE TITLE
[FE/TASK]주요 기능 구현1(landing page interaction)

### ISSUE THREAD

**Issue by jong-ah** [codestates/DEVzine-port#11]
## ISSUE
- Group:`Client`
- Type:`Feature`
- Detail:implement landing page interaction with Three.js 

## TODO
- [x] scroll 값에 따라 Three.js의 카메라 객체의 position 조작
- [x] smooth scroll 구현
- [x] mesh에 click event 발생 시 react-spring으로 animation 처리  

## Estimated Time
`12h`
