### ISSUE TITLE
[DEV LOG] 2021.08.12 강하은

### ISSUE THREAD

**Issue by vodkamitlime** [codestates/DEVzine-port#126]
## Contributions
- 서버 배포 test
    - redis → 에러 해결 (apt-get 말고 apt)
    - db → 문제 x
- 효승님과 백엔드 작업 계획 공유
    - 스택 정리
    - issue card
- Stats 모델 생성
- 크롤링 자동화, 주기 수정 (& utc 로 수정)
    - 24시간, 48시간 함수 분리
- VisualPage 함수 구현
    - Users 통계 완료 → 관련 API 수정
    - 캐싱 msg 분리

## Difficult point
- 배포 서버에서 늘 색다른 이유로 502 에러가 터지는 게 답답함 (많이 익숙해지긴 했어도 여전히 배포 올릴 때마다 불안함)

## TODO tomorrow
- [ ] Crawler 조회수 캐시 완성
- [ ] 배포 서버에서 automation (crawler) 작동하는지 확인 
- [ ] Visuals 코드에 Articles 통계 추가
