### ISSUE TITLE
[FE/TASK]주요 기능 구현2(visual page with animating chart)

### ISSUE THREAD

**Issue by jong-ah** [codestates/DEVzine-port#14]
## ISSUE
- Group:`Client`
- Type:`Feature`
- Detail:implement chart of visual page and scroll reveal effect 

## TODO
- [x] chart를 react에서 구현할 수 있는 방안 모색
- [x] data를 DB로부터 받아와 data 변동 시 chart가 유동적으로 변할 수 있도록 axios 요청 결과 값 반영
- [x] scroll reveal 효과를 적용 

## Estimated Time
`12h`
