### ISSUE TITLE
[FE/TASK] Landing Page 구현

### ISSUE THREAD

**Issue by jong-ah** [codestates/DEVzine-port#18]
## ISSUE
- Group:`Client`
- Type:`Feature`
- Detail:인터렉션 적용 및 서비스 기능 설명 

## TODO
- [x] 구현된 인터렉션 적용 및 인터렉션 완료 후 화면 구현
- [x] 스크롤에 따라 핵심기능설명 이미지가 보임
- [x] 회원 수 0에서부터 시작하여 전체수가 보이게 인터렉션 적용
- [x] 버튼에 알맞은 링크 이동
- [x] header, footer 적용
- [x] 반응형 구현

## Estimated Time
`12h`
