### ISSUE TITLE
[FE/TASK] Article List Page 구현

### ISSUE THREAD

**Issue by jong-ah** [codestates/DEVzine-port#21]
## ISSUE
- Group:`Client`
- Type:`Feature`
- Detail:기사 내용을 받아와 리스트화 및 정렬

## TODO
- [x] data를 DB에서 받아와 적용 
- [x] 최신순, 조회순으로 12개 기사글 정렬 (default 최신순)
- [x] 기사 마우스오버 시, 기사글 색 변화
- [x] 기사 클릭 시, 해당 기사 보기 페이지로 이동
- [x] 더보기 버튼 누르면 12개씩 기사글 추가
- [x] header, footer 적용
- [x] 반응형 구현

## Estimated Time
`12h`
