### ISSUE TITLE
[BE/TASK] 시각화를 위한 통계 자료

### ISSUE THREAD

**Issue by deprecated-ogu** [codestates/DEVzine-port#25]
## ISSUE
- Group : `server`
- Type : `feature`
- Detail : 크롤링한 데이터 기초 통계 분석 후 결과 전달

## TODO
- [x] get '/visual'
- [x] 유저 성별 통계
- [x] 현 시점으로부터 지난 한 달 간의 기사 분야별 갯수
- [x] 일별 기사 분야별 갯수

## Estimated Time
`Nh`
