### ISSUE TITLE
[DEV LOG] 2021.08.23 강하은

### ISSUE THREAD

**Issue by vodkamitlime** [codestates/DEVzine-port#277]
## Contributions
- [mypage] 다른 user 기고글 보이는 문제 → db 에 id 잘못 부여됨, fix 완료
- [mypage] magazine update 페이지 → 본인 기고글 수정용 endpoint 추가, api 수정
    - 토큰 유효성 검사 후 기고글 주인 맞는지 검사
    - 기고글 존재하는지 검사
    - 위 두 케이스 통과할 경우 기고글 정보 반환
- [mypage] → 삭제완료된 기고글 전송하지 않도록 수정
- [mypage] 이미 존재하는 아이디로 닉네입 변경 시 → 409 에러 (API 수정 완료)
- [mypage] 구독 정보 변경되도록 수정 
- [admin] 승인 이후 user_name 안 들어오는 issue 해결
- [admin] 관리자 로그아웃 기능 구현 
- [email] 구독자 발송 이메일 와이어프레임 제작
- [email] 구독 해지하기 엔드포인트, api 추가
- [email] 구독 해지하기 클라이언트 컴포넌트 추가 
- [email] ejs 파일 css 적용 모듈 추가
- [DB] contributions 컬렉션에 recommended 필드 추가 & 전체 값 false 설정 완료
- [DB] dummy data 에 user_name anonymous 계정 추가 완료 (회원탈퇴명 중복가입 방지)
- [Visual] 전체 키워드 누적 개수 조정 (보안 - 40)
- [회원 탈퇴] 탈퇴한 회원의 기고글 이메일 anonymous 로 수정
- [회원 탈퇴] 관리자 페이지, 개별 기고글 접속 시 탈퇴한 회원의 user_name 은 ananoymous 로 출력

## Difficult point
- CSS 와 html 태그를 오랜만에 공부하니 낯설고 어려움 

## TODO tomorrow
- [ ] DB 최적화 (오래된 DB 삭제)
- [ ] 서버 전체 리팩토링
- [ ] 캐시 최종 설정
