### ISSUE TITLE
[FE/TASK] SignUp Page 구현

### ISSUE THREAD

**Issue by jong-ah** [codestates/DEVzine-port#29]
## ISSUE
- Group:`Client`
- Type:`Feature`
- Detail:입력받은 사용자 정보를 유효성 검사 및 Post 요청

## TODO
- [x] 필수로 이메일, 비밀번호, 비밀번호 확인, 닉네임을 입력하게 함
- [x] 옵션으로 성별, 나이, 직무(단일선택), 언어(중복선택)을 입력하게 함
- [x] 유효성을 검사하여 제대로 작성되지 않을 시, 다시 작성하게 함
- [x] 회원가입 버튼을 누르면 작성된 내용을 post 요청
- [x] header, footer 적용
- [x] 반응형 구현

## Estimated Time
`12h`
