### ISSUE TITLE
[FE/TASK] MyPage 구현

### ISSUE THREAD

**Issue by jong-ah** [codestates/DEVzine-port#31]
## ISSUE
- Group:`Client`
- Type:`Feature`
- Detail:입력받은 사용자 정보를 가져오고, 수정하여 전달 

## TODO
- [x] 기존에 작성된 회원정보를 get 요청
- [x] 수정된 내용을 patch 요청
- [x] 로그인이 됐을 때만 마이페이지에 들어올 수 있음
- [x] 이메일 정보는 수정되지 않으며 그외 정보는 수정 가능 (회원가입에서 기입한 정보)
- [x] 구독여부와 게시여부를 마이페이지에서 확인 가능
- [x] 구독취소 가능
- [x] 자신의 신청한 기고글과 게시 여부를 확인 가능함 (대기, 승인, 거절)
- [x] header, footer 적용
- [x] 반응형 구현

## Estimated Time
`12h`
