### ISSUE TITLE
[FE/TASK] Article VIew Page 구현

### ISSUE THREAD

**Issue by jong-ah** [codestates/DEVzine-port#33]
## ISSUE
- Group:`Client`
- Type:`Feature`
- Detail: useParams로 열람하기 원하는 카테고리 및 컨텐츠 ID를 axios get 요청에 반영하여 다양한 카테고리를 하나의 component 안에서 볼 수 있게 구현 

## TODO
- [x] 개별 기사, 기고 글의 정보 get 요청 
- [x] 리스트 버튼을 누르면 Article List Page로 이동 
- [x] 로그인 전이라면 로그인/회원가입 버튼을 클릭하면 로그인 모달창 뜸
- [x] 로그인 후라면 전체 게시글 보기 버튼을 클릭하면 해당 게시글 링크로 이동하고 기고글은 전체를 보여주기
- [x] header, footer 적용
- [x] 반응형 구현

## Estimated Time
`12h`
