### ISSUE TITLE
[FE/TASK] Header 구현

### ISSUE THREAD

**Issue by jong-ah** [codestates/DEVzine-port#34]
## ISSUE
- Group:`Client`
- Type:`Feature`
- Detail:매 페이지마다 고정 위치, 어느창에서든 기능 가능하게 구현 

## TODO
- [x] 뉴스 갱신이 매일 am 7시에 이뤄짐으로 그에 맞춰 시간을 보여줌
- [x] 로그인 여부에 따라 문구 버튼 '여러분께' or 'OOO님께'
- [x] 로고를 누를 시 landing page로 이동
- [x] 로그인/로그아웃/구독 버튼을 누를 시 관련 모달창으로 뜸
- [x] header, footer 적용
- [x] 반응형 구현

## Estimated Time
`12h`
