### ISSUE TITLE
[FE/TASK] Footer 구현

### ISSUE THREAD

**Issue by jong-ah** [codestates/DEVzine-port#36]
## ISSUE
- Group:`Client`
- Type:`Feature`
- Detail:매 페이지마다 고정 위치, 어느창에서든 기능 가능하게 구현 

## TODO
- [x] 좌측엔 팀 정보를 입력
- [x] 우측엔 '기고 신청'과 '핵심 데이터 보기' 버튼이 있음
- [x] 기고 신청, 핵심 데이터 보기 버튼을 누를 시 관련 페이지으로 이동
- [x] header, footer 적용
- [x] 반응형 구현

## Estimated Time
`12h`
