### ISSUE TITLE
[BE/TASK] DB Seed Setting

### ISSUE THREAD

**Issue by vodkamitlime** [codestates/DEVzine-port#41]
## ISSUE
- Group : `DB`
- Type : `Setting`
- Detail : 설정된 스키마에 DB 시드 데이터 추가 

## TODO
- [x] DB 스키마에 맞게 dummy data 제작
- [x] DB Seed 추가
- [x] 각 테이블에서 자료 받아와지는지 test

## Estimated Time
`3h`
