### ISSUE TITLE
[FE/Task]  UI 디자인(데스크탑/태블릿/모바일)

### ISSUE THREAD

**Issue by jong-ah** [codestates/DEVzine-port#7]
## ISSUE
- Group:`Client`
- Type:`Feature`
- Detail: 반응형과 UX를 고려한 UI디자인   

## TODO
- [x] UI디자인 (데스트탑) - 총 14개 page 제작
- [x] UI디자인 (태블릿) - 총 14개 page 제작
- [x] UI디자인 (모바일) - 총 14개 page 제작

## Estimated Time
`2day`
