### ISSUE TITLE
[DEV LOG] 2021.08.09 강하은

### ISSUE THREAD

**Issue by vodkamitlime** [codestates/DEVzine-port#76]
## Contributions
- 배포시 DB 에 연결되지 않아 502 뜨는 에러 해결
- 새로 논의된 기능에 따른 DB Schema 및 Seed Data 수정 (기고)
- 새로 논의된 기능에 따른 DB Schema 및 아키텍쳐 구상 (관리자)
- 서버 Router 전체 세팅 및 수정 

## Difficult point
- localhost 에서는 문제가 생기지 않는 DB 연결 설정이 EC2 에서는 문제가 되는 경우 (대소문자 구분 등), 이에 따른 502 에러 원인을 발견하기 어려움 
`Solution: 하지만 이는 DB 담당자인 본인의 불찰이 크다고 생각함, 앞으로 모델명과 스키마 함수를 더욱 꼼꼼하게 확인할 것`
- 기능이 추가됨에 따라 DB 스키마와 Seed Data 에 변동사항이 생김, 이를 서버에 반영하려면 모든 Collection 을 재설정 해야 하기에 스트레스가 있음 
`Solution: 서비스가 커진 후 발생할 변동사항을 최소화하기 위해 (Advanced, Nightmare 중) 구현 가능성이 높은 범위까지는 미리 DB 에 포함해둘 것`

## TODO tomorrow
- [ ] DB 재설정 및 Schema, Seed Data 수정
- [ ] 웹 기사 Crawler 함수 1차 마무리 (필수 데이터 전부 긁어와서 DB 에 바로 입력 가능한 형태로 만들기)
- [ ] Redis Cache 연결 및 설정
